version: '3.8'

services:
  postgres:
    env_file:
      - .env.development.local
    container_name: postgres
    image: postgis/postgis:14-3.2
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    env_file:
      - .env.development.local
    container_name: redis
    image: redis:6.2-alpine
    restart: unless-stopped
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  malcy-backend:
    env_file:
      - .env.development.local
    container_name: malcy-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      FE_APP_HOST: ${FE_APP_HOST}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRES_IN: ${JWT_ACCESS_TOKEN_EXPIRES_IN}
      JWT_REFRESH_TOKEN_EXPIRES_IN: ${JWT_REFRESH_TOKEN_EXPIRES_IN}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    links:
      - postgres
      - redis

volumes:
  postgres-data:
